from __future__ import annotations

from pathlib import Path
from typing import Any

import joblib

from src.feature_builder import FeatureBuilder
from src.flow_generator import FlowRecord
from src.preprocess import Preprocessor


class DetectionEngine:
    def __init__(
        self,
        model_path: str | Path = "models/model.pkl",
        scaler_path: str | Path = "models/scaler.pkl",
        features_path: str | Path = "models/features.json",
    ) -> None:
        self.model_path = Path(model_path)
        self.feature_builder = FeatureBuilder(features_path)
        self.preprocessor = Preprocessor(scaler_path)
        self.model: Any | None = None
        if self.model_path.exists():
            self.model = joblib.load(self.model_path)

    def predict_flow(self, flow: FlowRecord) -> dict:
        vector = self.feature_builder.build_vector(flow)
        transformed = self.preprocessor.transform_one(vector)

        if self.model is None:
            return {
                "prediction": "suspicious",
                "confidence": "N/A",
                "features": vector,
                "details": "No model.pkl found. Demo fallback prediction used.",
            }

        prediction = self.model.predict(transformed)[0]
        confidence: float | str = "N/A"
        if hasattr(self.model, "predict_proba"):
            probabilities = self.model.predict_proba(transformed)[0]
            confidence = float(max(probabilities))

        return {
            "prediction": str(prediction),
            "confidence": confidence,
            "features": vector,
            "details": "Prediction generated by model.pkl.",
        }
